### PR TITLE
Fix gyro eclp bugs

### LINKED ISSUE #60: patch: eclp price inversion / token order bug
> When creating a pool, alpha and beta needs to be set as a range of token1/token2 where token1 is the lower address. For usdc/ws, ws is the lower address, so the range is ws/usdc. Meaning if I want to have a range from $0.4 - $1 of wS price, in this example, I need to set 0.4 as lowest price and 1 as highest price because wS is a lower address. There are two issues in the pool creator with this:

> A. The pool creator does not take the token address ordering into account when deploying. I.e. when I enter the range as usdc/wS (notice the inversion) as 1-3 it should invert that to 0.333 - 1 when deploying because wS is the lower address.When deploying a pool. The creator needs to check the correct token ordering and invert the lowest/highest price if needed. 

> B. I think it should show the natural ordering first based on token ordering

### PR DESCRIPTION
**Pull request by MattPereira**
https://docs.google.com/document/d/1A6C45DXbxb1vRfC6RV7UrH_kzTIRyM2vKdM9iMAo7h8/edit?tab=t.0

### Issue Discussion
- [x] #62
- [x] #58 
- [x] #60 
- [ ] #65 

image

image

### CODE REVIEW

File: packages/nextjs/app/v3/_components/ChooseParameters/EclpParams.tsx [hunk 1]
```diff
@@ -80,7 +80,7 @@ function ParamInputs() {
 
   const sortedTokens = tokenConfigs
     .map(token => ({ address: token.address, symbol: token.tokenInfo?.symbol }))
-    .sort((a, b) => (a.address > b.address ? 1 : -1));
+    .sort((a, b) => a.address.localeCompare(b.address));
```
Comment (MattPereira) [inline packages/nextjs/app/v3/_components/ChooseParameters/EclpParams.tsx:83]: I think this poorly executed token sort was the root of issue 4
https://docs.google.com/document/d/1A6C45DXbxb1vRfC6RV7UrH_kzTIRyM2vKdM9iMAo7h8/edit?tab=t.0
